
from __future__ import annotations

"""用户数据隔离模块。

按 user_id 隔离数据目录，为多用户场景打基础。
"""

from .capability_requests import (
    CreateCapabilityRequest,
    OwnerCapabilityRequest,
    close_capability_request,
    create_capability_request,
    expire_capability_requests,
    list_capability_requests,
)
from .context_bundle import (
    MainContextBundleRequest,
    MainContextBundleResult,
    build_main_context_bundle,
    latest_main_context_bundle_path,
)
from .home_backup import HomeBackupManifest, create_home_backup_manifest
from .home_index_rebuild import HomeIndexRebuildResult, rebuild_home_indexes
from .home_indexes import (
    AgentIndexRef,
    IndexRefsReport,
    RunIndexRef,
    TaskIndexRef,
    dangling_index_refs,
    latest_agent_refs,
    latest_agent_refs_report,
    latest_owner_refs,
    latest_owner_refs_report,
    latest_run_refs,
    latest_run_refs_report,
    latest_task_refs,
    latest_task_refs_report,
    register_agent_ref,
    register_owner_ref,
    register_run_ref,
    register_task_ref,
)
from .home_layout import ensure_my_agent_home, home_paths, resolve_my_agent_home
from .identity_store import (
    ProviderIdentityLookupReport,
    ProviderIdentityRecord,
    ProviderOwnerResolutionReport,
    ensure_canonical_user_profile,
    link_provider_identity,
    lookup_provider_identity,
    lookup_provider_identity_report,
    resolve_owner_from_provider_identity,
    resolve_owner_from_provider_identity_report,
)
from .owner_policy import (
    EffectiveOwnerPolicy,
    OwnerDiskUsage,
    OwnerPolicyBundle,
    OwnerPolicyBundleReport,
    owner_disk_usage,
    read_owner_policy_bundle,
    read_owner_policy_bundle_report,
    resolve_effective_owner_policy,
)
from .owner_resolver import (
    OwnerHomeResult,
    OwnerIdentity,
    ensure_owner_home,
    home_paths_with_owner,
    owner_identity_from_config,
    resolve_owner_home,
)
from .run_workspace import EnsureRunWorkspaceRequest, RunWorkspacePaths, ensure_run_workspace
from .temporary_grants import (
    CreateTemporaryGrant,
    OwnerTemporaryGrant,
    TemporaryGrantsReport,
    create_temporary_grant,
    expire_temporary_grants,
    list_temporary_grants,
    list_temporary_grants_report,
)

__all__ = [
    "CreateCapabilityRequest",
    "CreateTemporaryGrant",
    "HomeBackupManifest",
    "HomeIndexRebuildResult",
    "OwnerHomeResult",
    "OwnerMaintenanceResult",
    "OwnerCapabilityRequest",
    "OwnerDiskUsage",
    "OwnerIdentity",
    "OwnerPolicyBundle",
    "OwnerPolicyBundleReport",
    "OwnerRetentionPlan",
    "OwnerTemporaryGrant",
    "TemporaryGrantsReport",
    "EffectiveOwnerPolicy",
    "ProviderIdentityLookupReport",
    "ProviderOwnerResolutionReport",
    "ProviderIdentityRecord",
    "EnsureRunWorkspaceRequest",
    "MainContextBundleRequest",
    "MainContextBundleResult",
    "RunWorkspacePaths",
    "AgentIndexRef",
    "IndexRefsReport",
    "RunIndexRef",
    "RetentionAction",
    "TaskIndexRef",
    "apply_owner_retention",
    "build_home_doctor_report",
    "build_main_context_bundle",
    "close_capability_request",
    "create_capability_request",
    "create_home_backup_manifest",
    "create_temporary_grant",
    "dangling_index_refs",
    "ensure_canonical_user_profile",
    "ensure_owner_home",
    "ensure_my_agent_home",
    "ensure_run_workspace",
    "expire_capability_requests",
    "expire_temporary_grants",
    "home_paths",
    "home_paths_with_owner",
    "latest_main_context_bundle_path",
    "latest_owner_refs",
    "latest_agent_refs",
    "latest_agent_refs_report",
    "latest_owner_refs_report",
    "latest_run_refs",
    "latest_run_refs_report",
    "latest_task_refs",
    "latest_task_refs_report",
    "link_provider_identity",
    "list_capability_requests",
    "list_temporary_grants",
    "list_temporary_grants_report",
    "lookup_provider_identity",
    "lookup_provider_identity_report",
    "owner_identity_from_config",
    "owner_maintenance_due",
    "owner_disk_usage",
    "plan_owner_retention",
    "read_owner_policy_bundle",
    "read_owner_policy_bundle_report",
    "register_owner_ref",
    "register_agent_ref",
    "register_run_ref",
    "register_task_ref",
    "rebuild_home_indexes",
    "resolve_effective_owner_policy",
    "resolve_my_agent_home",
    "resolve_owner_home",
    "resolve_owner_from_provider_identity",
    "resolve_owner_from_provider_identity_report",
    "run_owner_retention_if_due",
]
