# LLM: Shared execution-contract artifact helpers keep task and real-task delivery setup in one generic place.
# 模块用途: 统一主代理 task/real-task 执行合同里的产物路径绑定、bootstrap 目标、startup actions 和 manifest 生成。

from __future__ import annotations

import json
from pathlib import Path

_PATH_CONTRACT_KEYS = ("workspace_relative_path", "resolved_path", "parent_dir", "artifact_root")
_CHECKPOINT_CONTRACT_KEYS = ("workspace_relative_path", "resolved_path", "parent_dir")


# LLM: build_artifacts_with_path_contracts binds artifact refs to the selected task workspace.
# 函数用途: 给 expected artifacts 增加 resolved path、artifact_root 和 staged checkpoint path 合同，避免模型从旧目录猜输出位置。
def build_artifacts_with_path_contracts(items: object, task_workspace: Path) -> list[dict[str, object]]:
    if not isinstance(items, list):
        return []
    return [_artifact_with_path_contract(dict(item), task_workspace) for item in items if isinstance(item, dict)]


# LLM: prepare_artifact_workspace materializes parent directories and a path manifest before model execution starts.
# 函数用途: 预创建产物父目录并写 `.my_agent_artifact_paths.json`，让执行链路从第一轮起就有稳定输出根。
def prepare_artifact_workspace(delivery_contract_path: Path, manifest_path: Path) -> None:
    payload = load_json_payload(delivery_contract_path)
    entries = _artifact_manifest_entries(payload)
    for entry in entries:
        Path(str(entry["parent_dir"])).mkdir(parents=True, exist_ok=True)
    write_json(manifest_path, {"schema_version": "artifact-path-manifest.v1", "artifacts": entries})


# LLM: build_bootstrap_contract derives generic start-work targets from structured artifact facts only.
# 函数用途: 生成通用开工合同，让主代理前几轮围绕 artifact/checkpoint 物化，而不是反复只读查看目录。
def build_bootstrap_contract(items: object) -> dict[str, object]:
    if not isinstance(items, list):
        return {"materialization_targets": [], "startup_actions": []}
    targets = _dedupe_materialization_targets(
        [
            *[_artifact_materialization_target(item) for item in items if isinstance(item, dict)],
            *[
                target
                for item in items
                if isinstance(item, dict)
                for target in _required_file_targets(item)
            ],
            *[
                target
                for item in items
                if isinstance(item, dict)
                for target in _checkpoint_targets(item)
            ],
        ]
    )
    return {"enforcement": "soft", "materialization_targets": targets, "startup_actions": _startup_actions(items)}


# LLM: load_json_payload reads small suite contracts generated by the planner.
# 函数用途: 读取 expected_artifacts/acceptance/delivery_contract JSON；失败时返回空对象并让后续验收失败。
def load_json_payload(path: Path) -> dict[str, object]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


# LLM: write_json centralizes deterministic UTF-8 JSON writing for execution artifacts.
# 函数用途: 写 manifest 等机器文件，字段排序便于 diff、恢复和审计。
def write_json(path: Path, payload: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True),
        encoding="utf-8",
    )


# LLM: _artifact_with_path_contract preserves existing artifact fields while adding machine path facts.
# 函数用途: 将 preferred_path 解析成 workspace 内绝对路径，并补齐 staging checkpoint 的绝对路径。
def _artifact_with_path_contract(item: dict[str, object], task_workspace: Path) -> dict[str, object]:
    preferred = str(item.get("preferred_path") or item.get("path") or "")
    resolved = _workspace_path(task_workspace, preferred)
    item["path_contract"] = {
        "workspace_relative_path": preferred,
        "resolved_path": str(resolved),
        "parent_dir": str(resolved.parent),
        "artifact_root": _root_segment(preferred),
    }
    contract = item.get("validation_contract")
    if isinstance(contract, dict):
        item["validation_contract"] = _validation_contract_with_checkpoint_paths(contract, task_workspace)
    return item


# LLM: _validation_contract_with_checkpoint_paths resolves staged refs without changing validator semantics.
# 函数用途: 给 staging_contract.checkpoint_refs 补充 checkpoint_paths，执行与恢复都读结构化路径。
def _validation_contract_with_checkpoint_paths(contract: dict[str, object], task_workspace: Path) -> dict[str, object]:
    updated = dict(contract)
    staging = updated.get("staging_contract")
    if not isinstance(staging, dict):
        return updated
    checkpoint_refs = staging.get("checkpoint_refs")
    if not isinstance(checkpoint_refs, list):
        return updated
    staging = dict(staging)
    staging["checkpoint_paths"] = [
        _checkpoint_path_contract(task_workspace, str(ref))
        for ref in checkpoint_refs
        if str(ref).strip()
    ]
    updated["staging_contract"] = staging
    return updated


# LLM: _checkpoint_path_contract keeps staged deliverables refs-first and workspace-bound.
# 函数用途: 为一个阶段产物生成相对路径、绝对路径和父目录三元组。
def _checkpoint_path_contract(task_workspace: Path, ref: str) -> dict[str, str]:
    resolved = _workspace_path(task_workspace, ref)
    return {
        "workspace_relative_path": ref,
        "resolved_path": str(resolved),
        "parent_dir": str(resolved.parent),
    }


# LLM: _artifact_manifest_entries extracts resolved artifact and checkpoint paths from one contract.
# 函数用途: 生成单独 manifest，便于工具、恢复和人工审计统一查看目标路径。
def _artifact_manifest_entries(payload: dict[str, object]) -> list[dict[str, str]]:
    entries: list[dict[str, str]] = []
    for artifact in payload.get("artifacts", []):
        if not isinstance(artifact, dict):
            continue
        path_contract = artifact.get("path_contract")
        if isinstance(path_contract, dict):
            entries.append({key: str(path_contract.get(key) or "") for key in _PATH_CONTRACT_KEYS})
        contract = artifact.get("validation_contract")
        staging = contract.get("staging_contract") if isinstance(contract, dict) else None
        if isinstance(staging, dict):
            entries.extend(_checkpoint_manifest_entries(staging.get("checkpoint_paths")))
    return entries


# LLM: _artifact_materialization_target turns one artifact path contract into the first delivery target.
# 函数用途: 给每个 artifact 生成最基础的“先让这个路径出现”的结构化目标。
def _artifact_materialization_target(item: dict[str, object]) -> dict[str, str]:
    path_contract = item.get("path_contract")
    if not isinstance(path_contract, dict):
        return {}
    return {
        "artifact_id": str(item.get("artifact_id") or ""),
        "kind": str(item.get("kind") or ""),
        "target_type": "artifact",
        "workspace_relative_path": str(path_contract.get("workspace_relative_path") or ""),
        "resolved_path": str(path_contract.get("resolved_path") or ""),
        "parent_dir": str(path_contract.get("parent_dir") or ""),
    }


# LLM: _required_file_targets expands directory-style validators into concrete early file targets.
# 函数用途: 如果验收合同声明 required_files，就把目录里的关键文件转成通用物化目标。
def _required_file_targets(item: dict[str, object]) -> list[dict[str, str]]:
    path_contract = item.get("path_contract")
    contract = item.get("validation_contract")
    if not isinstance(path_contract, dict) or not isinstance(contract, dict):
        return []
    required_files = contract.get("required_files")
    if not isinstance(required_files, list):
        return []
    root = Path(str(path_contract.get("resolved_path") or ""))
    relative_root = str(path_contract.get("workspace_relative_path") or "")
    targets: list[dict[str, str]] = []
    for name in required_files:
        file_name = str(name).strip()
        if not file_name:
            continue
        relative = str(Path(relative_root) / file_name).replace("\\", "/")
        resolved = root / file_name
        targets.append(
            {
                "artifact_id": str(item.get("artifact_id") or ""),
                "kind": str(item.get("kind") or ""),
                "target_type": "required_file",
                "workspace_relative_path": relative,
                "resolved_path": str(resolved),
                "parent_dir": str(resolved.parent),
            }
        )
    return targets


# LLM: _checkpoint_targets expands staged checkpoint contracts into early deliverable targets.
# 函数用途: 把 staging_contract.checkpoint_paths 变成结构化物化目标，供长任务先落阶段产物。
def _checkpoint_targets(item: dict[str, object]) -> list[dict[str, str]]:
    contract = item.get("validation_contract")
    if not isinstance(contract, dict):
        return []
    staging = contract.get("staging_contract")
    checkpoint_paths = staging.get("checkpoint_paths") if isinstance(staging, dict) else None
    if not isinstance(checkpoint_paths, list):
        return []
    targets: list[dict[str, str]] = []
    for checkpoint in checkpoint_paths:
        if not isinstance(checkpoint, dict):
            continue
        targets.append(
            {
                "artifact_id": str(item.get("artifact_id") or ""),
                "kind": str(item.get("kind") or ""),
                "target_type": "checkpoint",
                "workspace_relative_path": str(checkpoint.get("workspace_relative_path") or ""),
                "resolved_path": str(checkpoint.get("resolved_path") or ""),
                "parent_dir": str(checkpoint.get("parent_dir") or ""),
            }
        )
    return targets


# LLM: _dedupe_materialization_targets keeps bootstrap contracts compact and stable across retries.
# 函数用途: 按 resolved_path 去重，避免 artifact 本身和 checkpoint/required_file 重复显示。
def _dedupe_materialization_targets(items: list[dict[str, str]]) -> list[dict[str, str]]:
    seen: set[str] = set()
    deduped: list[dict[str, str]] = []
    for item in items:
        resolved = str(item.get("resolved_path") or "").strip()
        if not resolved or resolved in seen:
            continue
        seen.add(resolved)
        deduped.append(item)
    return deduped


# LLM: _startup_actions derives generic start-order hints from staged tool builders and target paths.
# 函数用途: 生成结构化开工动作，例如先物化 checkpoint，再调用 builder_tool，不依赖任务自然语言。
def _startup_actions(items: object) -> list[dict[str, object]]:
    if not isinstance(items, list):
        return []
    actions: list[dict[str, object]] = [{"action": "materialize_target", "priority": 1}]
    for item in items:
        if not isinstance(item, dict):
            continue
        actions.extend(_artifact_startup_actions(item))
    return actions


# LLM: _artifact_startup_actions expands one staged artifact into ordered startup actions.
# 函数用途: 从单个 artifact 的 staging_contract 提取 checkpoint 物化和 builder 调用动作。
def _artifact_startup_actions(item: dict[str, object]) -> list[dict[str, object]]:
    contract = item.get("validation_contract")
    staging = contract.get("staging_contract") if isinstance(contract, dict) else None
    if not isinstance(staging, dict):
        return []
    return [
        *_checkpoint_startup_actions(staging.get("checkpoint_refs")),
        *_builder_startup_actions(staging),
    ]


# LLM: _checkpoint_startup_actions converts checkpoint refs into first-round materialization actions.
# 函数用途: 为每个 checkpoint_ref 生成先写骨架的通用动作，帮助长任务尽早落地阶段文件。
def _checkpoint_startup_actions(items: object) -> list[dict[str, object]]:
    if not isinstance(items, list):
        return []
    actions: list[dict[str, object]] = []
    for ref in items:
        ref_text = str(ref or "").strip()
        if ref_text:
            actions.append({"action": "materialize_checkpoint", "priority": 1, "checkpoint_ref": ref_text})
    return actions


# LLM: _builder_startup_actions emits a single builder invocation hint when the staged contract names one.
# 函数用途: 把 builder_tool/source_ref/output_ref 转成统一动作，让后续 prompting 和 guard 读同一事实。
def _builder_startup_actions(staging: dict[str, object]) -> list[dict[str, object]]:
    builder_tool = str(staging.get("builder_tool") or "").strip()
    if not builder_tool:
        return []
    return [
        {
            "action": "invoke_builder_tool",
            "priority": 2,
            "builder_tool": builder_tool,
            "source_ref": _staging_source_ref(staging),
            "output_ref": _staging_output_ref(staging),
        }
    ]


# LLM: _staging_source_ref supports every structured source key used by builder contracts.
# 函数用途: 让 xlsx/pdf 等 builder 的 startup action 都带正确 source_ref。
def _staging_source_ref(staging: dict[str, object]) -> str:
    keys = [
        str(staging.get("source_ref_key") or "").strip(),
        str(staging.get("input_ref_key") or "").strip(),
        "source_json_ref",
        "source_markdown_ref",
        "source_ref",
        "input_ref",
    ]
    for key in keys:
        if not key:
            continue
        if value := str(staging.get(key) or "").strip():
            return value
    return ""


# LLM: _staging_output_ref supports every structured output key used by builder contracts.
# 函数用途: 让 workbook/pdf/output_ref 都能进入 startup action。
def _staging_output_ref(staging: dict[str, object]) -> str:
    keys = [
        str(staging.get("output_ref_key") or "").strip(),
        "workbook_ref",
        "pdf_ref",
        "output_ref",
        "artifact_ref",
    ]
    for key in keys:
        if not key:
            continue
        if value := str(staging.get(key) or "").strip():
            return value
    return ""


# LLM: _checkpoint_manifest_entries normalizes staged path contracts for the manifest.
# 函数用途: 收集 source_data/build_script/final_artifact 等阶段路径，统一预创建父目录。
def _checkpoint_manifest_entries(items: object) -> list[dict[str, str]]:
    if not isinstance(items, list):
        return []
    entries: list[dict[str, str]] = []
    for item in items:
        if isinstance(item, dict):
            entries.append({key: str(item.get(key) or "") for key in _CHECKPOINT_CONTRACT_KEYS})
    return entries


# LLM: _workspace_path resolves a structured relative ref under the task workspace.
# 函数用途: 解析产物路径并拒绝 `..` 逃逸，保持真实任务只能写入自己的 workspace。
def _workspace_path(task_workspace: Path, value: str) -> Path:
    candidate = Path(value)
    resolved = candidate if candidate.is_absolute() else (task_workspace / candidate).resolve()
    try:
        resolved.relative_to(task_workspace.resolve())
    except ValueError:
        return (task_workspace / "_invalid_artifact_path").resolve()
    return resolved


# LLM: _root_segment records the first relative path segment for output-root diagnostics.
# 函数用途: 提供 artifact_root 元数据，帮助后续 UI/恢复识别 outputs、reports 等产物区。
def _root_segment(value: str) -> str:
    parts = Path(value).parts
    return str(parts[0]) if parts and parts[0] not in {"", "."} else ""


__all__ = [
    "build_artifacts_with_path_contracts",
    "build_bootstrap_contract",
    "load_json_payload",
    "prepare_artifact_workspace",
    "write_json",
]
