
from __future__ import annotations

"""Markdown report rendering for the code-size checker."""

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class ReportRenderContext:
    mode: str
    blocked: bool
    baseline_path: str | None
    baseline_loaded: bool


def _format_table(findings: list[Any], limit: int = 0) -> list[str]:
    if not findings:
        return ["- none"]
    lines = [
        "| Severity | Kind | Path | Name | Value | Limit | Message |",
        "| --- | --- | --- | --- | ---: | ---: | --- |",
    ]
    items = findings[:limit] if limit > 0 else findings
    for item in items:
        lines.append(
            f"| {item.severity} | {item.kind} | `{item.path}` | `{item.name}` | "
            f"{item.value} | {item.limit} | {item.message} |"
        )
    if limit > 0 and len(findings) > limit:
        lines.append(f"| ... | ... | ... | ... | ... | ... | *{len(findings) - limit} more* |")
    return lines


def _section(title: str, findings: list[Any], limit: int = 0) -> list[str]:
    return ["", title, *_format_table(findings, limit)]


def _findings_by_kind(findings: list[Any]) -> dict[str, list[Any]]:
    kinds = {
        "file",
        "function",
        "class",
        "mixin",
        "params",
        "nesting",
        "high_risk_growth",
        "import_star",
        "decode_error",
        "junk_name",
    }
    return {kind: [item for item in findings if item.kind == kind] for kind in kinds}


def _summary_lines(findings: list[Any], context: ReportRenderContext) -> list[str]:
    hard = [item for item in findings if item.severity == "hard"]
    high_risk = [item for item in findings if item.severity == "high-risk"]
    soft = [item for item in findings if item.severity == "soft"]
    return [
        f"- mode: {context.mode}",
        f"- baseline: {context.baseline_path or 'none'}",
        f"- baseline_loaded: {context.baseline_loaded}",
        f"- blocked: {context.blocked}",
        f"- total_findings: {len(findings)}",
        f"- hard_findings: {len(hard)}",
        f"- high_risk_findings: {len(high_risk)}",
        f"- soft_findings: {len(soft)}",
    ]


def _finding_sections(findings: list[Any]) -> list[str]:
    by_kind = _findings_by_kind(findings)
    high_risk = [item for item in findings if item.severity == "high-risk"]
    soft = [item for item in findings if item.severity == "soft"]
    return [
        *_section("## 1. Oversized Files Top 20", by_kind["file"], 20),
        *_section("## 2. Oversized Functions Top 20", by_kind["function"], 20),
        *_section("## 3. Oversized Classes Top 20", by_kind["class"], 20),
        *_section("## 4. Oversized Mixins Top 20", by_kind["mixin"], 20),
        *_section("## 5. Too Many Params Top 20", by_kind["params"], 20),
        *_section("## 6. Deep Nesting Top 20", by_kind["nesting"], 20),
        *_section("## 7. High-risk / near-soft Top 100", high_risk, 100),
        *_section("## 8. High-risk File Growth", by_kind["high_risk_growth"]),
        *_section("## 9. import * Violations", by_kind["import_star"]),
        *_section("## 10. Decode Error Violations", by_kind["decode_error"]),
        *_section("## 11. Junk File / Junk Name Violations", by_kind["junk_name"]),
        *_section("## 12. Historical Soft Findings", soft[:100]),
    ]


def _recommendations() -> list[str]:
    return [
        "",
        "## 13. Next Recommendations",
        "- Keep `cli/parser.py` thin and route registration through `cli/commands/`.",
        "- Continue extracting `cli/chat.py` into chat session, input loop, renderer, and gateway client modules.",
        "- Move SubAgent mixin logic into services and repositories behind the manager facade.",
        "- Split memory archive query/runtime and log analysis tools by query, rendering, and persistence responsibilities.",
        "- Run `--write-baseline` to capture current state, then use `--mode strict --baseline` to block only new violations.",
    ]


def write_report(report_path: Path, findings: list[Any], context: ReportRenderContext) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    lines = [
        "# CODE SIZE REPORT",
        "",
        f"Generated at: {now}",
        f"Generated by: `python scripts/check_code_size.py --mode {context.mode}`",
        "",
        *_summary_lines(findings, context),
        *_finding_sections(findings),
        *_recommendations(),
        "",
        "## 14. Strict Blocked",
        f"- {'**yes**' if context.blocked else 'no'}",
        "",
    ]
    report_path.write_text("\n".join(lines), encoding="utf-8")
