from __future__ import annotations

"""Markdown report rendering for the code-size checker."""

from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _format_table(findings: list[Any], limit: int = 0) -> list[str]:
    if not findings:
        return ["- none"]
    lines = [
        "| Severity | Kind | Path | Name | Value | Limit | Message |",
        "| --- | --- | --- | --- | ---: | ---: | --- |",
    ]
    items = findings[:limit] if limit > 0 else findings
    for item in items:
        lines.append(
            f"| {item.severity} | {item.kind} | `{item.path}` | `{item.name}` | "
            f"{item.value} | {item.limit} | {item.message} |"
        )
    if limit > 0 and len(findings) > limit:
        lines.append(f"| ... | ... | ... | ... | ... | ... | *{len(findings) - limit} more* |")
    return lines


def _section(title: str, findings: list[Any], limit: int = 0) -> list[str]:
    return ["", title, *_format_table(findings, limit)]


def _recommendations() -> list[str]:
    return [
        "",
        "## 10. 下一步建议",
        "- Keep `cli/parser.py` thin and route registration through `cli/commands/`.",
        "- Continue extracting `cli/chat.py` into chat session, input loop, renderer, and gateway client modules.",
        "- Move SubAgent mixin logic into services and repositories behind the manager facade.",
        "- Split memory archive query/runtime and log analysis tools by query, rendering, and persistence responsibilities.",
        "- Run `--write-baseline` to capture current state, then use `--mode strict --baseline` to block only new violations.",
    ]


def write_report(
    report_path: Path,
    findings: list[Any],
    *,
    mode: str,
    blocked: bool,
    baseline_path: str | None,
    baseline_loaded: bool,
) -> None:
    hard = [item for item in findings if item.severity == "hard"]
    soft = [item for item in findings if item.severity != "hard"]
    by_kind = {kind: [item for item in findings if item.kind == kind] for kind in {
        "file", "function", "class", "nesting", "high_risk_growth",
        "import_star", "decode_error", "junk_name",
    }}
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    lines = [
        "# CODE SIZE REPORT",
        "",
        f"Generated at: {now}",
        f"Generated by: `python scripts/check_code_size.py --mode {mode}`",
        "",
        f"- mode: {mode}",
        f"- baseline: {baseline_path or 'none'}",
        f"- baseline_loaded: {baseline_loaded}",
        f"- blocked: {blocked}",
        f"- total_findings: {len(findings)}",
        f"- hard_findings: {len(hard)}",
        f"- soft_findings: {len(soft)}",
        *_section("## 1. 超长文件 Top 20", by_kind["file"], 20),
        *_section("## 2. 超长函数 Top 20", by_kind["function"], 20),
        *_section("## 3. 超长类 Top 20", by_kind["class"], 20),
        *_section("## 4. 高复杂度函数 Top 20", by_kind["nesting"], 20),
        *_section("## 5. 高危文件增长", by_kind["high_risk_growth"]),
        *_section("## 6. import * 违规", by_kind["import_star"]),
        *_section("## 7. decode error 违规", by_kind["decode_error"]),
        *_section("## 8. junk file / junk name 违规", by_kind["junk_name"]),
        *_section("## 9. 历史遗留项 (soft)", soft[:100]),
        *_recommendations(),
        "",
        "## 11. 本次是否阻断",
        f"- {'**yes**' if blocked else 'no'}",
        "",
    ]
    report_path.write_text("\n".join(lines), encoding="utf-8")
