
from __future__ import annotations

"""Markdown report rendering for the code-size checker."""

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from code_size_rules import is_test_path


@dataclass(frozen=True)
class ReportRenderContext:
    mode: str
    blocked: bool
    baseline_path: str | None
    baseline_loaded: bool


def _format_table(findings: list[Any], limit: int = 0) -> list[str]:
    if not findings:
        return ["- none"]
    lines = [
        "| Severity | Kind | Path | Name | Value | Limit | Message |",
        "| --- | --- | --- | --- | ---: | ---: | --- |",
    ]
    items = findings[:limit] if limit > 0 else findings
    for item in items:
        lines.append(
            f"| {item.severity} | {item.kind} | `{item.path}` | `{item.name}` | "
            f"{item.value} | {item.limit} | {item.message} |"
        )
    if limit > 0 and len(findings) > limit:
        lines.append(f"| ... | ... | ... | ... | ... | ... | *{len(findings) - limit} more* |")
    return lines


def _section(title: str, findings: list[Any], limit: int = 0) -> list[str]:
    return ["", title, *_format_table(findings, limit)]


def _findings_by_kind(findings: list[Any]) -> dict[str, list[Any]]:
    kinds = {
        "function",
        "class",
        "mixin",
        "params",
        "nesting",
        "import_star",
        "decode_error",
        "junk_name",
    }
    return {kind: [item for item in findings if item.kind == kind] for kind in kinds}


def _summary_lines(findings: list[Any], context: ReportRenderContext) -> list[str]:
    strict_findings = [item for item in findings if not _is_test_finding(item)]
    strict_hard = [item for item in strict_findings if item.severity == "hard"]
    strict_high_risk = [item for item in strict_findings if item.severity == "high-risk"]
    strict_soft = [item for item in strict_findings if item.severity == "soft"]
    test_advisory = [item for item in findings if _is_test_finding(item)]
    return [
        f"- mode: {context.mode}",
        f"- baseline: {context.baseline_path or 'none'}",
        f"- baseline_loaded: {context.baseline_loaded}",
        f"- blocked: {context.blocked}",
        f"- strict_scope_total_findings: {len(strict_findings)}",
        f"- strict_scope_hard_findings: {len(strict_hard)}",
        f"- strict_scope_high_risk_findings: {len(strict_high_risk)}",
        f"- strict_scope_soft_findings: {len(strict_soft)}",
        f"- test_advisory_findings: {len(test_advisory)}",
    ]


def _is_test_finding(item: Any) -> bool:
    return is_test_path(str(item.path))


def _finding_sections(findings: list[Any]) -> list[str]:
    strict_findings = [item for item in findings if not _is_test_finding(item)]
    test_findings = [item for item in findings if _is_test_finding(item)]
    by_kind = _findings_by_kind(strict_findings)
    high_risk = [item for item in strict_findings if item.severity == "high-risk"]
    soft = [item for item in strict_findings if item.severity == "soft"]
    return [
        *_section("## 1. Oversized Functions Top 20", by_kind["function"], 20),
        *_section("## 2. Oversized Classes Top 20", by_kind["class"], 20),
        *_section("## 3. Oversized Mixins Top 20", by_kind["mixin"], 20),
        *_section("## 4. Too Many Params Top 20", by_kind["params"], 20),
        *_section("## 5. Deep Nesting Top 20", by_kind["nesting"], 20),
        *_section("## 6. High-risk / near-soft Top 100", high_risk, 100),
        *_section("## 7. import * Violations", by_kind["import_star"]),
        *_section("## 8. Decode Error Violations", by_kind["decode_error"]),
        *_section("## 9. Junk File / Junk Name Violations", by_kind["junk_name"]),
        *_section("## 10. Historical Soft Findings", soft[:100]),
        *_section("## 11. Test Advisory Findings Top 100", test_findings, 100),
    ]


def _recommendations() -> list[str]:
    return [
        "",
        "## 12. Next Recommendations",
        "- Keep `cli/parser.py` thin and route registration through `cli/commands/`.",
        "- Continue extracting `cli/chat.py` into chat session, input loop, renderer, and gateway client modules.",
        "- Keep SubAgent manager as the readable owner of its main lifecycle, with services only where they remove real branching.",
        "- Split memory archive or log analysis only when one file owns unrelated query, rendering, and persistence responsibilities.",
        "- Run `--write-baseline` to capture current state, then use `--mode strict --baseline` to block only new violations.",
    ]


def write_report(report_path: Path, findings: list[Any], context: ReportRenderContext) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    lines = [
        "# CODE SIZE REPORT",
        "",
        f"Generated at: {now}",
        f"Generated by: `python scripts/check_code_size.py --mode {context.mode}`",
        "",
        *_summary_lines(findings, context),
        *_finding_sections(findings),
        *_recommendations(),
        "",
        "## 13. Strict Blocked",
        f"- {'**yes**' if context.blocked else 'no'}",
        "",
    ]
    report_path.write_text("\n".join(lines), encoding="utf-8")
